### ISSUE TITLE
Value should be a JSON object.

### ISSUE THREAD

**Issue by thiagoe** [Prototype-X/Zabbix-Template-Juniper-MX-BGP4-ipv4-ipv6#1]
This Really good template for juniper.  Thanks for share.

I have one little problem when ll use script LLD. My discovery rule show this message "Value should be a JSON object."
without Script, the discovery work fine but only show IPs as hex numbers.

any idea how to solve it?

Zabbix Version 3.0.3

**Comment by Prototype-X** [comment]
Hi. You can run script manually and show me output ./LLD.py -h 1.1.1.1 -c public
script return JSON or error. If you need use private chat on gitter.

**Comment by thiagoe** [comment]
Really thanks for reply.

Last Night i try your sugestion and receive this message "/usr/bin/env: python3: Arquivo ou diretório não encontrado"

So i reistaled phyton 3 and json work normally.

Sorry waste your time.

**Comment by Prototype-X** [comment]
It’s all right. :-)
