### ISSUE TITLE
Interface xe-

### ISSUE THREAD

**Issue by YSmetana** [Prototype-X/Zabbix-Template-Juniper-MX-BGP4-ipv4-ipv6#2]
Hello, just installed your template and its working great! Thanks! :)

Please consider to add new interface type **xe-** (onboard 10G XFP) to LLD interfaces filter.

    xe-0/0/0                up    up
    xe-0/0/1                up    down
    xe-0/0/2                up    down
    xe-0/0/3                up    down

**Comment by Prototype-X** [comment]
Hi, this filter is for example only. Typically, you need to change the filter for your needs. :)

**Comment by YSmetana** [comment]
OK, tnx! ;)
