### ISSUE TITLE
Template does not discover XE(10G) interfaces

### ISSUE THREAD

**Issue by apofiget** [Prototype-X/Zabbix-Template-Juniper-MX-BGP4-ipv4-ipv6#4]
Hi! 
Thanks for a template, it works well, but it doesn't discover 10Ge interfaces.
I think you need to fix regular expression in <discovery_rule> named "Junos interfaces".

**Comment by Prototype-X** [comment]
Hi!
This regular expression for example. You need edit or delete regular expression for your configuration.
Remove the regular expression to autodiscover all interfaces.

**Comment by apofiget** [comment]
Ok, thanks.

**Comment by ajcorrea** [comment]
@apofiget 
use this:

^(ms|ge|xe)-[0-2]\/[0-2]\/[0-9]$|^(ae|reth|st)[0-9]$|^fxp[0-9]-[0-9]+$|^vlan.[0-9]+$|^irb.[0-9]+$
